---
title: "News Archive"
---

* **June 2026**: Presented a talk titled *Generating function framework for spatiotemporal outbreak analytics* at [NetSci 2026](https://www.netsci2026.com/) in Boston.

* **December 2025**: Presented a poster titled *Modeling and optimization of multimodal travel-based surveillance at airports* at [Epidemics10](https://www.elsevier.com/events/conferences/all/international-conference-on-infectious-disease-dynamics) in San Diego.

* **February 2025**: Presented *Modeling disease spread with probability generating functions* at the WiNS online seminar.

* **September 2024**: Started as a Postdoctoral Researcher with the [Modeling of Biological and Socio-technical Systems](https://www.mobs-lab.org/) Lab and the [Network Science Institute](https://www.networkscienceinstitute.org/) at the [Roux Institute at Northeastern University](https://roux.northeastern.edu/nu_research/comp-med/) in Portland, ME.

* **July 2024**: Successfully [defended](https://www.youtube.com/watch?v=FQ_YMGxsWEk) my dissertation, *Probabilistic modeling of disease: Addressing uncertainties in within-host and population-level dynamics*.

* **June 2024**: Presented joint work, *Temporal and probabilistic comparisons of epidemic interventions*, at [NetSci 2024](https://netsci2024.com/en) in Québec City.

* **October 2023**: Completed my comprehensive exam, making me a Ph.D. Candidate in Mathematical Sciences!

* **October 2023**: Joint work with Andrea J. Allen, Nicholas J. Roberts, Antoine Allard, and Laurent Hébert-Dufresne, *Temporal and probabilistic comparisons of epidemic interventions* is now available on [Bulletin of Mathematical Biology](https://link.springer.com/article/10.1007/s11538-023-01220-w)!

* **September 2023**: Attended the [Grace Hopper Celebration for Women in Tech](https://ghc.anitab.org/) in Orlando, Florida to explore career opportunities and attend invited talks.

* **August 2023**: Presented a contributed talk titled *Sensitivity analysis of stochastic polynomials, and its application to epidemic forecasting and random graphs* at Contagion on Complex Social Systems Workshop 2023 at the University of Vermont.

* **May 2023**: Presented on the preprint titled *Temporal and probabilistic forecasts of epidemic interventions* at the Women in Network Science Minisymposium at [SIAM Dynamical Systems](https://www.siam.org/conferences/cm/conference/ds23) 2023 Conference in Portland, Oregon.

* **May 2023**: Attended the [Women in Network Science Collabathon](https://sites.google.com/view/womeninnetworkscience/meetings/collabathon-2023) at the Network Science Institute at Northeastern University.

* **April 2023**: Presented a poster titled *Temporal and probabilistic forecasts of epidemic interventions* at the [UVM Student Research Conference 2023](https://www.uvm.edu/four/uvm-src-2023).

* **April 2023**: Discussed how we can understand the world as networks on the [Math 4 All](https://www.youtube.com/watch?v=XuA3uKH3uRI&t=1108s) podcast.

* **February 2023**: Joint work with Andrea J. Allen, Nicholas J. Roberts, Antoine Allard, and Laurent Hébert-Dufresne, *Temporal and probabilistic forecasts of epidemic interventions* is now available on [arXiv](https://arxiv.org/abs/2302.03210)!

* **February 2023**: Joint work with Robyn M. Stuart, Jamie A. Cohen, Cliff C. Kerr, Romesh G. Abeysuriya, Marita Zimmerman, Darcy W. Rao, and Daniel J. Klein, *HPVsim: An agent-based model of HPV transmission and cervical disease* from my contract work with the Gates Foundation is now available on [medRxiv](https://www.medrxiv.org/content/10.1101/2023.02.01.23285356v1.full.pdf+html)!

* **May 2022**: Started my internship/contract work at the Institute for Disease Modeling at the Gates Foundation.
